In [2]:
include("LineFracGen.jl")
using Winston

In [10]:
function render(points, iterations, filename; path = pwd()*"\\renders", sig_loc = "LL")
    #saves fractal from 'points' with given 'iteration' at 'path' as 'filename' of size 'plotwidth' by 'plotheight'
    
    #generate and plot fractal
    fractal = frac(points, iterations) 
    p=plot(fractal[:,1],fractal[:,2],linewidth=.5)
    
    #locate signature spot
    xmin = minimum(fractal[:,1])
    xmax = maximum(fractal[:,1])
    ymin = minimum(fractal[:,2])
    ymax = maximum(fractal[:,2])
    
    ########### check for clear locations?
    
    #generate and plot signature
    if sig_loc == "LL" #signature location is lower left
        signature = sig(.015*(xmax-xmin),.03*(ymax-ymin),xmin,ymin) #.05 of total height, at lower left corner
    elseif sig_loc == "LR" #signature location is lower right
        signature = sig(.015*(xmax-xmin),.03*(ymax-ymin),xmax-.015*(xmax-xmin),ymin)
    end
        
    oplot(signature[:,1], signature[:,2], linewidth=.5)
    
    setattr(p.x1, draw_nothing = true)
    setattr(p.x2, draw_nothing = true)
    setattr(p.y1, draw_nothing = true)
    setattr(p.y2, draw_nothing = true)
    savefig(p, path*"\\"*filename*".pdf")
    savefig(p, path*"\\"*filename*".png", width = 4096, height=4096)
end

render (generic function with 3 methods)

render (generic function with 3 methods)

In [4]:
function renderloop(allpoints, iterations, filename ="", path = pwd()*"\\renders")
    #renders all the fractals in 'allpoints'
    
    for i = 1:size(allpoints,3)
        render(allpoints[:,:,i], iterations, filename * string(i), path)
    end
end

renderloop (generic function with 3 methods)

renderloop (generic function with 3 methods)

In [7]:
renderloop(goodones, 4, "n=4 ",  pwd()*"\\renders\\n=4")

In [11]:
#fix 11
render(goodones[:,:,11],4,"n=4 11", path=pwd()*"\\renders\\n=4", sig_loc = "LR")

In [5]:
function sig(width=1, height=1, xloc=0, yloc=0)
    #returns signature data points
    
    x = [0.25 0.5
         0.0 0.5
         0.0 0.25
         0.2 0.25
         0.0 0.25
         0.0 0.0
         0.25 0.0
         0.25 0.2
         0.25 0.0
         0.5 0.0#
         0.5 0.2
         0.34 0.2
         0.5 0.2
         0.5 0.4
         0.34 0.4
         0.5 0.4
         0.7 0.4
         0.5 0.4
         0.5 0.2
         0.66 0.2
         0.5 0.2
         0.5 0.0
         0.75 0.0
         0.75 0.2
         0.75 0.0
         1.0 0.0
         1.0 0.25
         0.8 0.25
         1.0 0.25
         1.0 0.5
         0.75 0.5]
    
    x *= [0 1; 1 0] #rotate
    x[:,1] .*= (2*width) #xscale. times 2 because default is only half a unit wide.
    x[:,2] .*= height #yscale. 
    x .+= [xloc yloc] #translate
    
    return x
end

sig (generic function with 5 methods)

sig (generic function with 5 methods)

In [11]:
#n=3

#initialize
goodones = zeros(3,2,3)
goodones[end,1,:] = 1
#fill with goodness
goodones[2,:,1] = [.5 -.6]
goodones[2,:,2] = [.5 -.5]
goodones[2,:,3] = [.5 -.4]

1x2 Array{Float64,2}:
 0.5  -0.4

In [6]:
#n=4

#initialize
goodones = zeros(4,2,32)
goodones[end,1,:] = 1
#fill with goodness
goodones[2:3,:,1] = [.375 -.31;.625 .31]
goodones[2:3,:,2] = [.4 -.8; .6 -.8]
goodones[2:3,:,3] = [.0 -.6; .8 -.6]
goodones[2:3,:,4] = [.0 -.6; .6 -.4]
goodones[2:3,:,5] = [.8 -.4;.2 -.4]
goodones[2:3,:,6] = [.0 -.6;.6 .0]
goodones[2:3,:,7] = [.2 -.6;.8 -.6]
goodones[2:3,:,8] = [.4 -.6;.6 -.6]
goodones[2:3,:,9] = [.6 -.6;.4 -.6]
goodones[2:3,:,10] = [-.4 -.4;.2 .0]
goodones[2:3,:,11] = [-.2 -.4;.6 -.4]
goodones[2:3,:,12] = [-.2 -.4;.4 .0]
goodones[2:3,:,13] = [-.2 -.4;.6 .0]
goodones[2:3,:,14] = [.0 -.4;.4 0]
goodones[2:3,:,15] = [.0 -.4;.6 .0]
goodones[2:3,:,16] = [.2 -.4;.8 -.4]
goodones[2:3,:,17] = [.2 -.4;.6 .0]
goodones[2:3,:,18] = [.4 -.4;1.2 -.2]
goodones[2:3,:,19] = [.6 -.4;.4 -.4]
goodones[2:3,:,20] = [-.6 -.2;.2 .2]
goodones[2:3,:,21] = [-.4 -.2;.4 -.2]
goodones[2:3,:,22] = [-.4 -.2;.4 .0]
goodones[2:3,:,23] = [-.2 -.2; .4 .0]
goodones[2:3,:,24] = [-.2 -.2;.4 .2]
goodones[2:3,:,25] = [.4 -.2;.6 .2]
goodones[2:3,:,26] = [.6 -.2;.2 -.2]
goodones[2:3,:,27] = [.6 -.2;.4 -.2]
goodones[2:3,:,28] = [.6 -.2;1.2 .0]
goodones[2:3,:,29] = [.8 -.2;.2 -.2]
goodones[2:3,:,30] = [.285 -.6;1-.285 -.6]
goodones[2:3,:,31] = [.6 -.8;.4 -.8]
goodones[2:3,:,32] = [.2 -.8;.8 -.8]

2x2 Array{Float64,2}:
 0.2  -0.8
 0.8  -0.8

2x2 Array{Float64,2}:
 0.2  -0.8
 0.8  -0.8